import { PlayerInterface } from "interfaces/PlayerInterface";
import { TankInterface } from "interfaces/TankInterface";
import { Wn8DetailsInterface } from "interfaces/Wn8DetailsInterface";

export interface TankStatInterface {
  player: PlayerInterface,
  tank: TankInterface,
  wn8: Wn8DetailsInterface | number,

  battle_life_time: number,
  battles: number,
  capture_points: number,
  created_at: string,
  damage_assisted_radio: number,
  damage_assisted_track: number,
  damage_dealt: number,
  damage_received: number,
  direct_hits_received: number,
  dropped_capture_points: number,
  efficiency: number,
  explosion_hits: number,
  explosion_hits_received: number,
  frags: number,
  hits: number,
  id: number,
  last_battle_time: string,
  losses: number,
  mark_of_mastery: number,
  max_frags: number,
  max_xp: number,
  no_damage_direct_hits_received: number,
  piercings: number,
  piercings_received: number,
  player_id: number,
  shots: number,
  spotted: number,
  survived_battles: number,
  tank_id: number,
  tank_tag: string,
  trees_cut: number,
  updated_at: string,
  weight: number,
  wins: number,
  wn7: number,
  xp: number,
}
